GET https://alek6.amorce.org/api/products
Accept: application/json


###


POST https://127.0.0.1:8000/api/login_check
Content-Type: application/json

{
    "username": "client@muse.com",
    "password": "Client12"
}


